disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - closure_spacing

line_length:
  warning: 80
  error: 100
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
  excluded:
    - id
    - x
    - y

excluded:
  - node_modules
  - dist
  - .build
  - build
  - DerivedData
  - ContentBlocker
  - scripts/xcode-manager/.build
  - scripts/xcode-manager/Package.resolved

reporter: "xcode"

